apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask
spec:
  restartPolicy: OnFailure
  containers:
    - name: flask
      image: codeislife771/flask-task-manager:latest
      ports:
        - containerPort: 5000
      envFrom:
        - configMapRef:
            name: flask-config  
      livenessProbe:
        httpGet:
          path: /tasks
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /tasks
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 5
